JakeStanger/ironbar

src/modules/launcher/item.rs, src/modules/launcher/mod.rs, src/modules/launcher/open_state.rs
[fix(launcher): opening new instances when focused/urgent](https://github.com/JakeStanger/ironbar/commit/b81927e3a57808188e31419695a36aa4ea3f2830)
[fix(launcher): item state changes not handled correctly](https://github.com/JakeStanger/ironbar/commit/a35d25520cd3fd235cdc77ec6209d88499ca3639)
=> Fix launcher state issues

Cargo.lock, Cargo.toml, examples/sys-info.corn, src/modules/sysinfo.rs
Fixes #15 and fixes #17, and also massively reduces the memory usage. Yay!
=> Add loads more tokens & interval options to `sysinfo`, optimise info refreshing

docs/Configuration guide.md, docs/Scripts.md, docs/_Sidebar.md, src/bar.rs, src/config.rs, src/modules/clock.rs, src/modules/custom.rs, src/modules/focused.rs, src/modules/launcher/mod.rs, src/modules/mpd.rs, src/modules/script.rs, src/modules/sysinfo.rs, src/modules/tray.rs, src/modules/workspaces.rs, src/script.rs
The first three of many options that are common to all modules.
Includes documentation for each new option.
Resolves #36. Resolves partially #34.
=> feat: common module options (`show_if`, `on_click`, `tooltip`)

Cargo.lock, Cargo.toml, src/bar.rs, src/bridge_channel.rs, src/clients/wayland/client.rs, src/clients/wayland/toplevel.rs, src/config.rs, src/dynamic_string.rs, src/error.rs, src/logging.rs, src/macros.rs, src/main.rs, src/modules/clock.rs, src/modules/custom.rs, src/modules/focused.rs, src/modules/launcher/item.rs, src/modules/launcher/mod.rs, src/modules/mod.rs, src/modules/mpd.rs, src/modules/script.rs, src/modules/sysinfo.rs, src/modules/tray.rs, src/modules/workspaces.rs, src/script.rs, src/style.rs
=> General refactoring and tidy-up

Cargo.lock, Cargo.toml, src/clients/system_tray.rs
It ain't perfect but it'll do.
Resolves #2.
=> fix(tray): some init issues

.github/workflows/build.yml, Cargo.lock, Cargo.toml, README.md, docs/Compiling.md, src/bar.rs, src/clients/compositor/mod.rs, src/clients/mod.rs, src/clients/music/mod.rs, src/config/impl.rs, src/config/mod.rs, src/image/gtk.rs, src/image/mod.rs, src/image/provider.rs, src/modules/launcher/mod.rs, src/modules/mod.rs
Flags allow you to disable certain functionality and compile with only select features to reduce build time.
Resolves #54.
=> feat: add feature flags

docs/Configuration guide.md, src/bar.rs, src/config/mod.rs
Adds a config option for adding margins around the bar.
=> Add configurable margins around bar

README.md, flake.nix
=> Add initial nix flags impl

Cargo.lock, Cargo.toml, src/config/impl.rs, src/main.rs, src/modules/custom.rs, src/modules/launcher/mod.rs
- Switches config implementation for [universal-config](https://github.com/jakestanger/universal-config).
- General refactoring to go with it
=> Use `universal-config` crate for config

README.md, flake.nix, nix/default.nix
=> Fix home manager module, and features

docs/_Sidebar.md, docs/modules/Label.md, examples/config.corn, examples/config.json, examples/config.toml, examples/config.yaml, src/bar.rs, src/config/mod.rs, src/dynamic_string.rs, src/modules/label.rs, src/modules/mod.rs
Takes a text label, with the ability to include embedded scripts.
Resolves #80.
=> feat: new label module

docs/Configuration guide.md, src/bar.rs, src/config/mod.rs, src/popup.rs
Adds new top-level `popup_gap` option.
=> feat: ability to configure popup gap

docs/modules/Custom.md, src/image/provider.rs, src/modules/custom/box.rs, src/modules/custom/image.rs, src/modules/custom/mod.rs, src/modules/custom/slider.rs
Resolves #94.
Also includes some general refactoring/fixes.
=> Custom image dynamic src support

src/script.rs
The short input parser was previously splitting colons, and incorrectly handling situations where the `cmd` section contained colons. The parser now properly checks input in the `mode:interval:cmd` format, moving onto the next section regardless of whether the previous was found.
This means unless your script literally starts with `poll:` or `5000:` you won't hit this issue anymore.
Hopefully resolves #94.
=> fix(script): parser incorrectly handling colons

src/modules/tray.rs, src/script.rs
Previously icons were only loaded from the theme based on the provided icon name. Sometimes no icon name was provided, and sometimes the name is just missing from the theme.
This falls back to using the provided pixbuf, and then falls back to just displaying the name as text if that is not available.
(Hopefully) resolves #99
=> fix(tray): icons sometimes not showing

src/dynamic_string.rs
=> fix(dynamic string): crash when last segment is static and a single char

docs/Configuration guide.md, docs/modules/Custom.md, src/modules/custom/slider.rs
=> Custom slider widget step option

src/image/provider.rs
Sets scale of icons when loading from theme.
=> fix(image): not scaling images for hidpi

docs/modules/Custom.md, src/modules/custom/slider.rs
Adds new `show_label` option.
Resolves #115 (for real this time).
=> feat(custom): option to toggle slider label

src/main.rs
This ensures that starting `ironbar` while an instance already running causes the 2nd instance to cleanly exit, and avoids launching the init code a second time.
=> fix: bars duplicate when starting second instance

Cargo.lock, Cargo.toml
Adds configuration support for `.ron` files https://github.com/ron-rs/ron
=> build: enable support for `ron` config lang

Cargo.lock, Cargo.toml, src/clients/clipboard.rs, src/clients/music/mpris.rs, src/clients/wayland/client.rs, src/clients/wayland/macros.rs, src/clients/wayland/mod.rs, src/clients/wayland/wl_output.rs, src/clients/wayland/wl_seat.rs, src/clients/wayland/wlr_data_control/device.rs, src/clients/wayland/wlr_data_control/manager.rs, src/clients/wayland/wlr_data_control/mod.rs, src/clients/wayland/wlr_data_control/offer.rs, src/clients/wayland/wlr_data_control/source.rs, src/clients/wayland/wlr_foreign_toplevel/handle.rs, src/clients/wayland/wlr_foreign_toplevel/manager.rs, src/clients/wayland/wlr_foreign_toplevel/mod.rs, src/config/common.rs, src/desktop_file.rs, src/dynamic_string.rs, src/error.rs, src/logging.rs, src/macros.rs, src/main.rs, src/modules/clipboard.rs, src/modules/focused.rs, src/modules/launcher/item.rs, src/modules/launcher/mod.rs, src/modules/launcher/open_state.rs
This is pretty much a rewrite of the Wayland client code for `wayland-client` and `wayland-protocols` v0.30.0, and `smithay-client-toolkit` v0.17.0.
- Fixes #41
- Fixes partially #86
- Some minor related tweaks/refactorings
=> Update Wayland libraries

CONTRIBUTING.md, README.md
Makes the README a lot prettier, changes some wording. 
Updates the contribution guidelines to enforce conventional commit.
=> README Overhaul / Contribution Guidelines Update

src/image/provider.rs
Adds in proper HiDPI image support into the image provider, using calls to Cairo.
Resolves #96 at last! (I hope...)
=> fix(image): still blurry on hidpi

src/modules/music/config.rs
=> fix: broken nerd font icons

docs/modules/Upower.md, src/modules/upower.rs
Reduces icon size, moves icon to inside button (before label).
=> Upower icon fixes

src/modules/focused.rs
=> Fix focused icon issues

.github/workflows/build.yml
=> ci: add caching support

Cargo.toml, src/desktop_file.rs
=> Add Support For Flatpak Icons

docs/modules/Music.md, src/clients/music/mod.rs, src/clients/music/mpd.rs, src/clients/music/mpris.rs, src/modules/music/mod.rs
Resolves #128.
Also includes a fix to ensure elements in the popup are hidden if the connected player is not capable of providing the info.
=> Music progress/seek bar

docs/Controlling Ironbar.md, src/ipc/commands.rs, src/ipc/server.rs, src/main.rs
=> feat(ipc): reload config command

Cargo.lock, Cargo.toml, docs/modules/Clock.md, src/modules/clock.rs
=> feat(clock): localization support

src/desktop_file.rs
Potentially also fixes some mismatches with icons.
Fixes #222.
=> fix(launcher): incorrectly resolving some applications

docs/Controlling Ironbar.md, src/bar.rs, src/global_state.rs, src/gtk_helpers.rs, src/image/gtk.rs, src/ipc/commands.rs, src/ipc/mod.rs, src/ipc/server.rs, src/main.rs, src/modules/clipboard.rs, src/modules/clock.rs, src/modules/custom/box.rs, src/modules/custom/button.rs, src/modules/custom/image.rs, src/modules/custom/label.rs, src/modules/custom/mod.rs, src/modules/custom/progress.rs, src/modules/custom/slider.rs, src/modules/focused.rs, src/modules/label.rs, src/modules/launcher/item.rs, src/modules/launcher/mod.rs, src/modules/mod.rs, src/modules/music/mod.rs, src/modules/script.rs, src/modules/sysinfo.rs, src/modules/tray.rs, src/modules/upower.rs, src/modules/workspaces.rs, src/popup.rs
Also includes some refactoring around related GTK helper code
Resolves #91
=> feat(ipc): commands for opening/closing popups

src/modules/launcher/mod.rs
=> Launcher focus fixes

.github/workflows/build.yml
=> ci(build): add nix caching

src/image/provider.rs
Puts a cap on the recursion, and falls back to a question mark image from the icon theme if no image could be resolved.
Fixes #250
=> feat(image resolver): add fallback image

src/desktop_file.rs, src/image/gtk.rs, src/image/provider.rs, src/modules/custom/image.rs, src/modules/focused.rs, src/modules/launcher/item.rs, src/modules/music/mod.rs, src/modules/upower.rs
Includes several small fixes and optimizations.
Fixes #228.
=> Image fixes

flake.lock, flake.nix, nix/default.nix
Right now the builder is on crane, but it's switchable to naersk (one string)
=> ci(nix): Add Crane and Naersk builders

Cargo.lock, Cargo.toml, src/clients/compositor/hyprland.rs
=> build: update to latest hyprland-rs

src/modules/launcher/item.rs, src/modules/launcher/mod.rs
=> fix(launcher): popup not closing when hover leaves widget

Cargo.lock, Cargo.toml, src/clients/system_tray.rs, src/modules/tray.rs
=> build: replace `stray` with `system-tray` fork

src/modules/focused.rs
=> fix(focused): clear when no window is focused

docs/modules/Sys-Info.md
Use - instead of _ for [sensor], as in #129
=> Fix cpu temp examples

src/modules/launcher/mod.rs
=> fix(launcher): favourites not focused when opened

src/clients/wayland/mod.rs, src/script.rs
=> Fix script crash

src/cli.rs
=> fix(cli): error when launched via `swaybar_command`

docs/Compiling.md, examples/style.css, src/desktop_file.rs
docs: add info on speeding up compilation time
refactor(desktop file): simplify some none-type handling
docs(examples): fix issues with example css
=> Various Small Changes

docs/Compiling.md
As suggested here: https://github.com/JakeStanger/ironbar/pull/417#issuecomment-1909308742
=> docs(compilation): add sccache section

src/clients/wayland/wlr_data_control/mod.rs
Thanks to a nightly clippy warning which found I wasn't using `file.write` correctly.
Fixes #86.
=> fix(clipboard): unable to paste large images into xwayland

src/modules/workspaces.rs
=> fix(workspaces): favourites not persisting for initially open workspaces

src/image/provider.rs, src/modules/tray/icon.rs, src/modules/upower.rs
=> Few small refactors

docs/modules/Tray.md, src/image/provider.rs, src/modules/tray/icon.rs, src/modules/tray/interface.rs, src/modules/tray/mod.rs
Fixes potentially/partially #452 
Fixes #455
=> More tray fixes

.github/scripts/ubuntu_setup.sh, .github/workflows/binary.yml, .github/workflows/build.yml, .github/workflows/deploy.yml, Cross.toml
=> ci: Build binaries on new tag.

src/modules/tray/interface.rs
=> fix(tray): cannot activate menu options with right click

nix/default.nix
=> build(nix): fix naersk build broken when using non-default features

docs/modules/Custom.md, src/modules/custom/button.rs
=> feat(custom): ability to add modules/widgets to buttons

Cargo.lock, Cargo.toml, src/clients/compositor/sway.rs
Trying to trim the build time wherever possible.
=> build: remove some unused features/deps

docs/Controlling Ironbar.md, src/ipc/commands.rs, src/ipc/server.rs, src/ironvar.rs
Adds new IPC/CLI command for listing all current ironvars and their values.
=> feat(ipc): ironvar list command

flake.nix, nix/default.nix
Tidies up the nix files a bit and fixes a couple of issues.
=> Nix refactor

docs/modules/Workspaces.md
The toml example currently doesn't work. This changes it so it does
=> Update workspaces module wiki

src/modules/focused.rs
=> fix(focused): incorrectly clearing when unfocused window title changes

examples/config.corn, examples/config.json, examples/config.toml, examples/config.yaml
update wrong audio volume percentage token
=> chore: update wrong audio volume percentage token

src/clients/compositor/hyprland.rs, src/clients/compositor/mod.rs, src/clients/compositor/sway.rs, src/modules/workspaces.rs, test-configs/workspaces.corn
=> fix(workspaces): regression due to #572

src/clients/wayland/wlr_foreign_toplevel/mod.rs
=> fix(launcher): ghost windows in reload

src/main.rs
This is a nasty hack, which will hopefully only be temporary.
See https://github.com/swaywm/sway/issues/8164 for details
=> fix: all bars showing on same display due to GTK bug

Cargo.lock, Cargo.toml, src/clients/wayland/wlr_data_control/mod.rs, src/clients/wayland/wlr_data_control/offer.rs
=> refactor: update `nix` crate to latest version

src/modules/launcher/mod.rs
=> fix(launcher): favourites staying focused when closed in hyprland

README.md, docs/Compiling.md, docs/Configuration guide.md, docs/modules/Upower.md, examples/config.corn, examples/config.json, examples/config.toml, examples/config.yaml, examples/test.corn
Resolves a few minor issues with documentation
Resolves #558 
Resolves #593 
Resolves #607
=> Documentation fixes

src/modules/notifications.rs
=> fix(notifications): unable to click through overlay

src/dynamic_value/dynamic_string.rs, src/gtk_helpers.rs, src/modules/clock.rs, src/modules/custom/button.rs, src/modules/custom/label.rs, src/modules/focused.rs, src/modules/label.rs, src/modules/music/mod.rs, src/modules/notifications.rs, src/modules/script.rs, src/modules/sysinfo.rs, src/modules/tray/interface.rs, src/modules/upower.rs, src/modules/volume.rs
Reverts JakeStanger/ironbar#621
Created more issues than it resolved
=> Revert "Fix Pango markup not escaped"

src/clients/wayland/wlr_foreign_toplevel/handle.rs
=> fix(launcher): apps with multiple windows stay focused when window closed

src/modules/music/mod.rs
=> fix(music): tokens with `&` not rendering

src/clients/swaync/mod.rs
=> fix(notifications): client broken by recent refactor

src/bar.rs, src/main.rs, src/popup.rs
=> fix: popups not accounting for monitor scaling

src/clients/mod.rs, src/clients/upower.rs, src/main.rs, src/modules/upower.rs
=> fix(upower): avoid panic on client init error

src/clients/music/mpris.rs
=> refactor(mpris): better logging, avoid panic on dbus error

src/modules/workspaces.rs
=> fix(workspaces): incorrectly checking focus using name_map value

src/clients/wayland/wlr_foreign_toplevel/mod.rs
=> fix(launcher): showing xwayland menus and tooltips

src/bar.rs, src/clients/music/mpris.rs, src/clients/sway.rs, src/clients/wayland/wlr_foreign_toplevel/handle.rs, src/config/impl.rs, src/ipc/server/bar.rs, src/main.rs, src/modules/cairo.rs, src/modules/sway/mode.rs, src/modules/sysinfo.rs, src/modules/tray/icon.rs, src/popup.rs
Hurray for tiny codebase improvements
=> refactor: fix some pedantic clippy warnings

src/dynamic_value/dynamic_string.rs, src/gtk_helpers.rs, src/modules/custom/button.rs, src/modules/custom/label.rs, src/modules/label.rs, src/modules/music/mod.rs, src/modules/script.rs, src/modules/sway/mode.rs, src/modules/sysinfo.rs, src/modules/upower.rs
=> fix: markup escape issues

src/ipc/server/mod.rs, src/main.rs, src/style.rs
=> fix: not properly redrawing on style reload

docs/modules/Clock.md, docs/modules/Tray.md, src/modules/tray/interface.rs, src/modules/tray/mod.rs
=> Fix tray focus issues on Sway

docs/Controlling Ironbar.md, src/cli.rs, src/ipc/responses.rs, src/ipc/server/bar.rs, src/main.rs
=> Allow IPC to act on multiple bars by the same name

src/clients/libinput.rs
=> fix(keys): high cpu usage

Cargo.toml, README.md, docs/Compiling.md, docs/modules/Workspaces.md, src/clients/compositor/hyprland.rs, src/clients/compositor/mod.rs, src/clients/compositor/niri/connection.rs, src/clients/compositor/niri/mod.rs, src/clients/compositor/sway.rs, src/modules/workspaces/button.rs, src/modules/workspaces/button_map.rs, src/modules/workspaces/mod.rs
Adds support to the Workspaces module for Niri
Supersedes #726 
Resolves #650
=> feat(workspaces): niri support

src/clients/volume/mod.rs, src/clients/volume/sink.rs, src/clients/volume/sink_input.rs, src/modules/volume.rs
=> chore: add trace logging to volume module

src/modules/custom/mod.rs
=> fix(custom): buttons lock up on long running commands

Cargo.lock, Cargo.toml, src/modules/cairo.rs
Updates to latest v0.10.3 version
=> refactor: update `mlua` crate

.github/workflows/docker.yml, Dockerfile
Adds Dockerfile which provides environment in which Ironbar can be built, to be used by CI
=> ci: add dockerfile for build image

.github/workflows/build.yml, .github/workflows/deploy.yml, .github/workflows/schema.yml, .github/workflows/wiki.yml
Adds a lot of jobs. This may be overkill.
=> ci(build): check each feature individually

src/clients/music/mpris.rs
Closes #970
Tested it in Firefox, mpv and Telegram, seems to work well
=> fix(mpris client): use set_position instead of seek

src/modules/cairo.rs
Fixes increasing the reference count of the `Context` without ever decreasing it.
Fixes #972
=> fix(cairo): huge memory leak

Cargo.lock, Cargo.toml, src/clients/compositor/hyprland.rs
=> refactor: update hyprland-rs, remove `expect`s from hyprland client code

src/clients/compositor/hyprland.rs, src/clients/compositor/sway.rs
Fixes a couple of compilation errors introduced by previous commit.
=> build: fix issues with compositor feature flags

src/clients/compositor/niri/mod.rs
=> fix(workspaces): reload broken on niri

docs/modules/Custom.md, src/modules/custom/box.rs
Closes #985
This implementation makes a working solution possible for the issue described in #985. I'm a little surprised the issue regarding box alignment wasn't raised by someone in the past unless I'm missing something.
Documentation has also been written for the added feature.
Thanks.
=> feat: add halign option to box module

docs/Controlling Ironbar.md, src/ipc/client.rs, src/ipc/server/mod.rs
=> fix(ipc): message size limited to 1024 bytes

Cargo.lock, Cargo.toml, docs/_Sidebar.md, docs/modules/Bluetooth.md, examples/style.css, src/clients/bluetooth.rs, src/clients/mod.rs, src/config/mod.rs, src/modules/bluetooth/config.rs, src/modules/bluetooth/mod.rs, src/modules/mod.rs, test-configs/bluetooth.corn
Bluetooth module via `bluer` crate. I think it is complete now.
=> feat: bluetooth module

src/modules/custom/mod.rs, src/modules/mod.rs
=> fix(custom): spaces in class names not handled

src/image/gtk.rs
=> feat: support pango markup in icon buttons

src/clients/volume/mod.rs, src/clients/volume/sink.rs, src/clients/volume/sink_input.rs, src/modules/volume.rs
Previously volume was only adjusted when the slider was released, due to an implementation issue where otherwise the server got overwhelmed and Ironbar hard-crashed.
This fixes the issue with the client code to properly support changing volume rapidly, and adjusts the UI code accordingly.
=> feat(volume): adjust smoothly as slider is dragged

.github/workflows/binary.yml
=> ci(binary): use arm image instead of cross

.github/scripts/ubuntu_setup.sh, Cross.toml
Remove cross config and cross-specific scripting since arm build now happens on arm image directly
=> build: remove cross

src/clients/mod.rs, src/clients/tray.rs
=> fix(tray): menu buttons work on single screen only
