Cargo.lock
Cargo.toml
examples/custom.corn
src/bar.rs
src/config.rs
src/main.rs
src/modules/custom.rs
src/modules/mod.rs
src/modules/script.rs
src/script.rs

Allows basic modules to be created from a config object, including popup content.
For example, this config (+ some CSS):
```corn
let {
$power_menu = {
type = "custom"
class = "power-menu"
bar = [ { type = "button" name="power-btn" label = "" exec = "popup:toggle" } ]
popup = [ {
type = "box"
orientation = "vertical"
widgets = [
{ type = "label" name = "header" label = "Power menu" }
{
type = "box"
widgets = [
{ type = "button" class="power-btn" label = "<span font-size='40pt'></span>" exec = "!shutdown now" }
{ type = "button" class="power-btn" label = "<span font-size='40pt'></span>" exec = "!reboot" }
]
}
]
} ]
}
} in {
end = [ { type = "clock" } $power_menu ]
}
```
Produces:
I think this is the best way to handle #10.

feat: new custom module

---

Cargo.lock
Cargo.toml
docs/modules/Script.md
src/modules/script.rs

You can now specify `mode =  "watch"` for scripts and they will spawn a long-running process, then update the label every time a new line is written to stdout.
Resolves #30

feat(script): new watch mode

---

.github/workflows/build.yml
.github/workflows/update-nix-flake-lock.yml
README.md
flake.lock
flake.nix

Adds nix flake with Home manager module for configuring, package for installing, and dev shell for development. Basically everything you will probably need to do with nix.
Though I didn't add non-flake support, since most people use flakes, but that can be easily added with https://github.com/edolstra/flake-compat.
<details>
<summary>And here is usage example (indentation is messed up, forgot to format 💀)</summary>
```nix
{ config, pkgs, ... }: {
programs.ironbar = {
enable = true;
config = let 
#workspaces = {
#	# 	_1 = "fire";
#};
launcher = {
type = "launcher";
favorites = ["firefox" "Steam"];
show_names = false;
show_icons = true;
icon_theme = "Papirus";
};
mpd_local = { type = "mpd"; music_dir = "/home/jake/Music"; };
#mpd_server = { type = "mpd" host = "localhost:6600" }
sys_info = …
```

Add nix flake

---

docs/Configuration guide.md
docs/Scripts.md
src/bar.rs
src/config/impl.rs
src/config/mod.rs

Adds `on_click_middle`, `on_click_right`, `on_scroll_up`, `on_scroll_down`.
BREAKING CHANGE: `on_click` is now called `on_click_left` for consistency with new options.
Resolves #44.

feat: mouse event config options

---

docs/modules/Music.md
src/modules/music.rs
src/modules/script.rs

Adds new `truncate.mode` and `truncate.length` options, and `truncate` shorthand for mode.
Resolves #56.

feat(music): ability to truncate button text

---

src/clients/compositor/hyprland.rs
src/clients/compositor/mod.rs
src/clients/compositor/sway.rs
src/modules/workspaces.rs

Fixes a couple of issues where switching workspaces rapidly on Hyprland (or sometimes not so rapidly) could cause the widget to come out of sync

fix(hyprland): issues with tracking workspaces

---

src/dynamic_string.rs

Fixes scripts inside dynamic strings such as tooltips and custom element labels not respecting their configured order.
Fixes #69

Fix dynamic string ordering

---

docs/Configuration guide.md
src/bar.rs
src/config/mod.rs

Adds `on_mouse_enter` and `on_mouse_exit` common module options.
Resolves #70.

feat: module hover options

---

flake.nix
nix/default.nix

So, I had copied Hyprland's nix pkg metadata as a boilerplate, and forgot to replace one of the strings with `ironbar`, and someone brought it up with me that it was erroring weirdly, and so I fixed it, and also added direct support for `nix run` by defining `apps.<system>.default` instead of making it use a fallback ;). Also, I have tested this locally, can't show screenshot, because ironbar spits out a lot of stuff to stdout, and so I lost the output :P.

Fix `nix run` support

---

docs/modules/Custom.md
src/modules/custom/box.rs
src/modules/custom/mod.rs

Adds the ability to use common module-level options inside custom module widgets.
Resolves #74.

feat(custom): support common options in widgets

---

src/bar.rs
src/config/common.rs
src/config/mod.rs
src/modules/custom/mod.rs
src/modules/mod.rs

Resolves #72.
You can control the behaviour using two new `transition_type` and  `transition_duration` module-level options. Defaults to enabled with a 250ms slide animation.

feat: wrap modules in a revealer to support animated show/hide

---

Cargo.lock
Cargo.toml
docs/modules/Upower.md
src/bar.rs
src/clients/mod.rs
src/clients/upower.rs
src/config/mod.rs
src/modules/mod.rs
src/modules/upower.rs

There are a couple of issues:
1) I want to use the popup to show additional details like time to empty/full and battery levels of other connected devices like bluetooth headphones. I've hardcoded the function for now but nothing happens when I click the module
2) upower will tell me what icon to use depending on battery level and whether it is plugged in, how do I implement this? I did `    format: "icon:{icon} {percentage}%"` in config.yaml but that doesn't seem to work
Broadly it seems to work fine

implement upower module

---

src/modules/tray.rs

Duplicates #65 because I cannot update `oknozor/master` directly.

fix: fallback to default icon theme for notifier items

---

docs/Configuration guide.md
docs/Styling guide.md
docs/modules/Clipboard.md
docs/modules/Clock.md
docs/modules/Custom.md
docs/modules/Focused.md
docs/modules/Label.md
docs/modules/Launcher.md
docs/modules/Music.md
docs/modules/Script.md
docs/modules/Sys-Info.md
docs/modules/Tray.md
docs/modules/Upower.md
docs/modules/Workspaces.md
examples/style.css
scripts/migrate-styles.sh
src/bar.rs
src/config/common.rs
src/gtk_helpers.rs
src/image/gtk.rs
src/main.rs
src/modules/clipboard.rs
src/modules/clock.rs
src/modules/custom/mod.rs
src/modules/focused.rs
src/modules/launcher/mod.rs
src/modules/mod.rs
src/modules/music/mod.rs
src/modules/sysinfo.rs
src/modules/upower.rs

BREAKING CHANGE: To allow for the `name` property, any widgets that were previously targeted by name should be targeted by class instead. This affects **all modules and all popups**, as well as several widgets inside modules.
**This will break a lot of rules in your stylesheet**. To attempt to mitigate the damage, a migration script can be found [here](https://raw.githubusercontent.com/JakeStanger/ironbar/master/scripts/migrate-styles.sh) that should get you most of the way.
Resolves #75.

[BREAKING] module-level `name` and `class` options

---

src/script.rs

fix: scripts don't work while running ironbar under a systemd service

---

src/image/gtk.rs
src/image/provider.rs
src/modules/custom/image.rs
src/modules/focused.rs
src/modules/launcher/item.rs
src/modules/music/mod.rs
src/modules/upower.rs

Previously images that could not be located were handled by throwing a full report error, which incorrectly stated it was an invalid image *type*.
This changes the image handling to instead log a single-line warning directly in the image provider code, reducing the error handling required by each consumer.
Resolves #146.

fix: poor error handling for missing images

---

src/clients/music/mpris.rs

The music module expects an event to be sent on subscription to the client to set up the initial state. This ensures an event is sent when in MPRIS mode when no player is initially found.

fix(music): showing when no mpris player found

---

Cargo.lock
Cargo.toml
docs/modules/Clipboard.md
docs/modules/Music.md
docs/modules/Workspaces.md
src/image/gtk.rs
src/modules/music/mod.rs

BREAKING CHANGE: Where both textual and image icons are supported, CSS classes have changed to better reflect their targets. `.icon` has changed to `.icon-box` and `.icon` now targets the underlying element. `.label` has been changed to `.icon.text-icon`. This affects icons on the **music**, **workspaces**, and **clipboard** modules.
Resolves #185.

fix: add sensible class names for icon labels

---

Cargo.lock
Cargo.toml
flake.lock
nix/default.nix
src/clients/system_tray.rs

This updates the `Cargo.toml` to add a patch for `stray`, which includes some fixes to stop it hard-crashing, while I wait for the PR to be merged.
Offers a partial resolve for #166

Use patched version of `stray`

---

src/modules/launcher/mod.rs

Attempting to focus a newly opened window from the launcher popup attempted to close the popup directly in an invalid manner, which caused the bar to hard crash. The controller already handles this correctly, so removed this code.
Resolves #41 :tada:

fix(launcher): crash when focusing newly opened window in popup

---

docs/modules/Upower.md
src/modules/upower.rs

Adds missing `icon_size` config option to upower module.

feat(upower): icon size option

---

src/desktop_file.rs

Applications installed via the Home Manager on Nixos are missing icons on the taskbar.  This patch searches for additional application paths using the XDG_DATA_DIR environment variable.

Find Additional Applications dirs in XDG_DATA_DIR

---

docs/Configuration guide.md
docs/Controlling Ironbar.md
src/bar.rs
src/config/mod.rs
src/ipc/commands.rs
src/ipc/server.rs

Adds a `set_visible` IPC command which takes a boolean `visibility` and string `bar_name` fields.
Simultaneously adds a new config `name` option to name each bar individually (defaults to the monitor name)
Behavior as-is will show/hide *every* bar with a given name. e.g, 2 bars both with the name `test` will be shown/hidden if we pass
`{"type":"set_visible","visible"=true,bar_name="test"}`

[Feature] Add basic bar visibility change to IPC

---

docs/modules/Workspaces.md
src/clients/compositor/hyprland.rs
src/clients/compositor/mod.rs
src/clients/compositor/sway.rs
src/modules/workspaces.rs

Adds CSS class `visible` to all workspace buttons whose workspaces are visible (displayed on a monitor), including the focused workspace. Like `focused`, the rule is `.workspaces .item.visible`.
Implementation replaces `focused: bool` of `clients::compositor::Workspace` with `visibility: Visibility`, which represents focused, visible, and hidden (not on a monitor). Both compositors' listeners now fill the changed field, `clients::compositor::WorkspaceUpdate::Focus` now carries `Workspace`s rather than workspace names, and `modules::workspaces::WorkspacesModule` now adds/removes the new CSS class according to the `Workspace`s.
Fixes #282

feat(workspaces): visible CSS selector

---

src/desktop_file.rs
src/style.rs

Possibly resolves the same issue with other editors or scripts.
Fixes #304

Fix style hot reloading when editing with Vim

---

flake.nix

The option for wayland.windowManager.hyprland.systemdIntegration has been renamed to wayland.windowManager.hyprland.systemd.enable as of home-manager commit ed0770e96225f998ea128549ad446d9b1568cb2c. 
The option for wayland.windowManager.sway.systemdIntegration has been renamed to wayland.windowManager.sway.systemd.enable as of home-manager commit 0144ac418ef633bfc9dbd89b8c199ad3a617c59f. 
Using the systemdIntegration options will still work for as long as the corresponding mkRenamedModuleOption stays in the respective home-manager modules but using the old option triggers a warning about the the renamed options.

fix: Home Manager systemdIntegration warnings

---

docs/Configuration guide.md
src/main.rs

This allows you to configure a default bar to use, then override specific monitors.
Not setting anything at the top level will hide bars which are not explicitly configured.
This actually came about as a bug in the recent refactorings, but now it's a feature :)

feat: use top-level config as fallback when using monitor-based config

---

docs/Configuration guide.md
src/bar.rs
src/config/mod.rs
src/main.rs

Adds two new bar-level options:
- `start_hidden`, which stops a bar from showing when Ironbar starts. It can then be hidden via IPC or auto-hide.
- `autohide`, which takes a delay after which the bar will be hidden when the cursor leaves. Hovering at the screen edge where the bar is located reveals the bar again.
Resolves #167

feat: bar auto-hide options

---

src/main.rs

Fixes a crash introduced by commit bea442e where the `await_sync` function incorrectly tried to use the current tokio runtime, which it is often outside, instead of the singleton.
Fixes #382

fix: some modules crashing due to recent gtk refactor

---

Cargo.lock
Cargo.toml
src/clients/compositor/hyprland.rs
src/clients/compositor/mod.rs
src/clients/compositor/sway.rs
src/config/mod.rs
src/dynamic_value/dynamic_bool.rs
src/dynamic_value/dynamic_string.rs
src/image/provider.rs
src/ipc/server.rs
src/macros.rs
src/modules/clipboard.rs
src/modules/clock.rs
src/modules/custom/progress.rs
src/modules/custom/slider.rs
src/modules/launcher/mod.rs
src/modules/mod.rs
src/modules/music/mod.rs
src/modules/upower.rs
src/modules/workspaces.rs
src/style.rs

Important commits:
**fix(regression): GTK refactor causing updates to be missed**
Regression introduced by recent GTK refactor.
The `glib_recv` macros  previously using the passed in expression as the receiver, which was causing a new receiver to be created *every* time an event was received. This caused some peculiar behaviours where some events just never got through if sent too close to each other.
This was most obvious in the `workspaces` module.
Fixes #381
**fix(workspaces): favourites missing `inactive` class on startup**
Fixes #390

Workspace Issues Fixes

---

src/bar.rs
src/clients/wayland/mod.rs
src/clients/wayland/wl_output.rs
src/error.rs
src/ipc/server.rs
src/main.rs

Finally, Ironbar will respond to events of monitors being (dis)connected, and will create bars when a monitor connects.
This means at last - resolves #291
yaay

feat: load bars on monitor when it connects

---

Cargo.toml
docs/Compiling.md
docs/modules/Clipboard.md
docs/modules/Focused.md
docs/modules/Launcher.md
src/bar.rs
src/clients/wayland/mod.rs
src/clients/wayland/wlr_foreign_toplevel/mod.rs
src/config/mod.rs
src/modules/mod.rs

Implementation to solve issue [403](https://github.com/JakeStanger/ironbar/issues/403). Please tell me if there is something I should change or refactor.

Make feature flags for the "focused" and launcher "modules"

---

src/style.rs

Fixes that changes were not hot-loaded when overriding the default style path with `IRONBAR_CSS` and providing a relative file path.

fix(style): file watcher not working for relative paths

---

docs/Ironvars.md
src/dynamic_value/dynamic_string.rs

Two fixes related to Ironvars in dynamic strings, a documentation correction, and an accompanying test.
Fixes #418

Dynamic String Fixes

---

docs/modules/Clock.md
src/modules/clock.rs

hello! this PR makes a simple change to allow the use of pango markup in clock formats. the plain `label` module does this, so I figured it wouldn't be out of place.
I read in the contributing guidance to open an issue or discussion as best practice, but since this is so small and I wanted it for myself I figured I'd just go straight to PR and I can close or revise it as you like.
thanks for writing ironbar!

feat: enable use of markup in clock module formats

---

docs/modules/Upower.md
src/modules/upower.rs

Adds parsing in format for properties other than {percentages} :face_with_spiral_eyes: 
Resolves #440

feat(upower): add new formatting properties

---

docs/modules/Upower.md

Docs have a type: the token is actually `time_remaining` and not `remaining`
Thought it'd be pretty annoying for users to not see the intended behavior

docs: correct formatting token time_remaining in upower module

---

README.md
src/logging.rs

Log files are now created on a daily rotation, keeping 3 days worth of logs. This also changes the log file names.
Fixes #453

fix(logging): log file growing indefinitely

---

docs/modules/Tray.md
src/modules/tray/mod.rs

Add the `direction` option for the tray module, giving the ability for vertical trays.
**Note:** This also sets the direction `top_to_bottom` *by default* for vertical bars. This is technically a **breaking change**, but I imagine nobody actually wants a horizontal tray on a vertical bar.

Add `direction` option for tray module

---

src/bar.rs
src/config/impl.rs
src/ipc/server.rs
src/modules/custom/mod.rs
src/modules/focused.rs
src/modules/launcher/item.rs
src/modules/launcher/mod.rs
src/modules/mod.rs
src/modules/sysinfo.rs
src/modules/tray/mod.rs
src/modules/workspaces.rs
src/popup.rs

Popups will now correctly re-anchor themselves to the button that opened them if the content resizes. 
This should also fix some long-standing issues where popups are occasionally opened in the wrong place first time they are opened.

fix(popup): re-position on resize due to content change

---

.github/workflows/build.yml
README.md

Changes to CI build jobs to do away with the old Nix job now we have Garnix, and split up the main build job to hopefully make things easier to read (and a bit faster).

Rewrite CI build workflow

---

src/modules/launcher/item.rs

When using spotify in wayland with hyprland, the spotify icon is not pulled up correctly by the launcher module:
`spotify --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland`
The class/app_id is "" while the name/title is "Spotify Premium". This uses item.name as a fallback which ensure spotify icon shows up correctly under wayland. Spotify under X11 does not have this problem.
Refs: #228, #146

feat(launcher): item.name as fallback for app icon

---

.github/workflows/build.yml
.github/workflows/deploy.yml
Cargo.lock
Cargo.toml
README.md
docs/Compiling.md
docs/_Sidebar.md
docs/modules/Volume.md
examples/config.corn
examples/style.css
flake.nix
nix/default.nix
src/bar.rs
src/clients/mod.rs
src/clients/volume/mod.rs
src/clients/volume/sink.rs
src/clients/volume/sink_input.rs
src/config/mod.rs
src/macros.rs
src/modules/mod.rs
src/modules/volume.rs

The volume module is now complete and stable enough that I believe it warrants opening a PR. The code is a bit rough in places so I'm going to refactor it over the next couple of weeks before it gets merged in. This hopefully also gives a chance for people to have a poke at it.
The initial version of the module provides the following:
- A button on the bar which indicates volume level by icon
- A popup with controls for output device switching, output device volume changing, and individual output stream (ie per program) level controls.
- Support for Pulseaudio (inc pipewire-pulse).
To do still:
Resolves #50

Volume module

---

src/clients/music/mod.rs
src/clients/music/mpris.rs

Sometimes, I see the NoActivePlayer DBusError when no music players are running.
```
2024-03-03T21:41:53.536515Z ERROR ironbar::logging: 48: The application panicked (crashed).
Message:  Failed to connect to D-Bus: DBusError(TransportError(D-Bus error: No player is being controlled by playerctld (com.github.altdesktop.playerctld.NoActivePlayer)))
Location: src/clients/music/mpris.rs:40
```
The first commit prevents the panic so the song shows when the player is started after ironbar was launched.
The second commit checks if all the players have been cleared out and sends None to hide the label in this case. With this change, the music label does not stay after the app is closed.
I tested by
1.start ironbar
2. then spotify,
3. then another player
4. and closed both
5. and restarted …

Fix(music): mpris - handle no active mpris player on launch & hide label when player list is empty.

---

docs/Configuration guide.md
src/bar.rs
src/config/impl.rs
src/config/mod.rs
src/main.rs

This allows for some options which are not actually bar-level to be separated, which makes some work moving forward a little easier and keeps things cleaner.

refactor: split bar/top-level config structs

---

docs/Configuration guide.md
docs/modules/Custom.md
src/bar.rs
src/config/common.rs
src/config/mod.rs
src/ipc/server.rs
src/macros.rs
src/modules/clipboard.rs
src/modules/clock.rs
src/modules/custom/mod.rs
src/modules/focused.rs
src/modules/label.rs
src/modules/launcher/mod.rs
src/modules/mod.rs
src/modules/music/mod.rs
src/modules/notifications.rs
src/modules/script.rs
src/modules/sysinfo.rs
src/modules/tray/mod.rs
src/modules/upower.rs
src/modules/volume.rs
src/modules/workspaces.rs
src/popup.rs

Adds ability to put native modules inside custom modules.
This works apart from a few (relatively) edge case. The code also needs refactoring.
Sticking this up for now so it's available - will revisit to get across the line in the near future.
Resolves #131.

Native modules inside custom modules

---

.github/scripts/ubuntu_setup.sh
Cargo.lock
Cargo.toml
docs/Compiling.md
docs/_Sidebar.md
docs/modules/Cairo.md
flake.nix
lua/draw.lua
lua/init.lua
nix/default.nix
shell.nix
src/clients/lua.rs
src/clients/mod.rs
src/config/mod.rs
src/main.rs
src/modules/cairo.rs
src/modules/mod.rs

This is an early working draft of the Cairo module, which allows you to write custom Lua scripts to draw whatever you like to a region of the bar. It's pretty rough around the edges but just about good enough to start playing with.
Currently this cannot be used in popups, however that will change fairly soon once #131 is resolved (that's been brought forward specifically because of this).
You need LuaJIT installed along with the [LGI](https://github.com/lgi-devs/lgi) package (`lua-lgi` on Arch). This needs to be installed to the `LUA_PATH` and `LUA_CPATH` respectively. If installing system-wide, this should Just Werk as it's in `/usr`.
I have played around with the idea of vendoring but suspect I will need to write bindings to statically link `lua-lgi` and its scripts into the Ironbar …

feat: new cairo module

---

src/modules/tray/icon.rs

Simple change to swap the channel order of the incoming pixmap data from ARGB to RGBA before creating the pixbuf.
Using the same icon as the one I added in the issue, it now renders like this, which is much more accurate to the original.
Also I'm still very new to rust, so if there's a cleaner way to do this please let me know.
Fixes #546

Fix #546: Convert from ARGB32 to RGBA32 formats for Pixmaps

---

docs/modules/Launcher.md
src/modules/launcher/mod.rs

example json config
{
"type": "launcher",
"favorites": [
"firefox",
"discord",
"steam"
],
"reversed": true,
"show_names": false,
"show_icons": true,
"icon_size": 32
}

Add reverse order for launcher items/favorites

---

.github/workflows/binary.yml

Please check the [releases](https://github.com/slowsage/ironbar/releases) and [actions](https://github.com/slowsage/ironbar/actions) log on fork's master branch to verify. [Master](https://github.com/slowsage/ironbar/commits/master/) is ahead of this commit.
Was pretty easy to add check and handle failures:
Here is the order of Binary runs in [actions](https://github.com/slowsage/ironbar/actions) log.
1. Deploy => binary succeeds. assets uploaded to v0.15.1
2. Deploy and binary failed.
3. workflow_dispatch - succeeds, uploads to v0.15.2
4. Manual release. succeeds, uploads to v0.15.3
Edit: The basic idea is to keep deploy.yml independent and bind to last release ref manually which automatically enabled `workflow_dispatch`.

fix(ci): Trigger Binary workflow on workflow_run, workflow_dispatch.

---

.github/workflows/binary.yml

Sorry, one oversight: The zip file uses github.ref_name which resolves to master. This uses the release tag instead. Verified [here](https://github.com/slowsage/ironbar/releases/tag/v0.15.4).
You can run  again using `workflow_dispatch` to fix the name for `v0.15.0`.

ci(binary): use release tag instead of github.ref_name

---

Cargo.lock
Cargo.toml
src/clients/compositor/hyprland.rs
src/clients/compositor/mod.rs
src/modules/workspaces.rs

Renaming workspaces on Hyprland will now work as expected.
This also refactors the workspace code to depend on IDs rather than names which should make it more robust against the same sort of issue in future.
Fixes #469
---
Draft until new hyprland-rs alpha releases

fix(workspaces): add support for hyprland rename event

---

src/image/gtk.rs
src/modules/music/mod.rs

Adds to `music` module formatting string, and all textual icon options.
Resolves #443

Add pango markup support to remaining locations

---

src/main.rs

let index = match index {
Some(index) => index - 1,
None => {
lock!(map).push(monitor_name.clone());
lock!(map).len() - 1
}
};
//This causes index to underflow
//Expected Output is something like 0, 1, etc
//But sometimes we go back around to 18446744073709551615
//Removing the index -1 here seems to work ok with multi monitor, and reload is not broken anymore
Fixes #598

Fix reload bug

---

src/config/common.rs
src/config/mod.rs
src/config/truncate.rs
src/modules/cairo.rs
src/modules/clipboard.rs
src/modules/clock.rs
src/modules/custom/box.rs
src/modules/custom/button.rs
src/modules/custom/image.rs
src/modules/custom/label.rs
src/modules/custom/mod.rs
src/modules/custom/progress.rs
src/modules/custom/slider.rs
src/modules/focused.rs
src/modules/label.rs
src/modules/launcher/mod.rs
src/modules/music/config.rs
src/modules/notifications.rs
src/modules/script.rs
src/modules/sysinfo.rs
src/modules/tray/mod.rs
src/modules/upower.rs
src/modules/volume.rs
src/modules/workspaces.rs

This is part of an upcoming effort to generate documentation from code.
Pushing this out before that stage so that the JSON schema is fully documented.

docs: add rustdoc comments to all module options

---

src/dynamic_value/dynamic_string.rs
src/gtk_helpers.rs
src/modules/clock.rs
src/modules/custom/button.rs
src/modules/custom/label.rs
src/modules/focused.rs
src/modules/label.rs
src/modules/music/mod.rs
src/modules/notifications.rs
src/modules/script.rs
src/modules/sysinfo.rs
src/modules/tray/interface.rs
src/modules/upower.rs
src/modules/volume.rs

Fixes issues where eg song title could contain an `&`, which would not display and log a GTK warning.

Fix Pango markup not escaped

---

README.md

Adds Fedora COPR package install instructions.
COPR: https://copr.fedorainfracloud.org/coprs/victorvintorez/tilingtools/
Build File: https://github.com/victorvintorez/Fedora-Packages/blob/master/ironbar/ironbar.spec
Automatic builds on new releases is intended but not implemented yet.

docs: add fedora copr package to readme

---

flake.nix

Adds the option to import a style.css file for the home-manager `programs.ironbar.style` option, instead of only accepting strings.
Resolves #655

feat: Add home-manager option to read style.css file

---

Cargo.lock
Cargo.toml
docs/Compiling.md
docs/_Sidebar.md
docs/modules/Network-Manager.md
src/clients/mod.rs
src/clients/networkmanager.rs
src/config/mod.rs
src/modules/mod.rs
src/modules/networkmanager.rs

Implements a module displaying (very) basic network connectivity from NetworkManager.
First step towards resolving #148.

Add NetworkManager module

---

src/modules/tray/icon.rs

fix(tray): crash when provided empty pixmap

---

Cargo.toml
docs/_Sidebar.md
docs/modules/Sway-mode.md
src/clients/compositor/mod.rs
src/clients/compositor/sway.rs
src/clients/mod.rs
src/clients/sway.rs
src/config/mod.rs
src/modules/mod.rs
src/modules/sway/mod.rs
src/modules/sway/mode.rs

Add a new module, similar to the waybar "sway/module" module. It shows the current mode under sway. For that, it needs to communicate with the Sway IPC. In this PR, the module is called "sway-mode" because "sway/mode" didn't work in my YAML config file (it would probably work if I surrounded it with quotes, but I didn't test).
This PR has two commits: the first one implements the module using a new sway connection. The second one refactors the sway `Client`, under `clients::compositor::sway`, to allow dynamically registering events, instead of only handling Workspace update ones. This second commit avoid creating a new socket for each module that needs to communicate with the Sway IPC, not sure if that is a problem to begin with.

Feat: sway-mode module

---

flake.nix

The icon theme was moved in the nixpkgs repo and this fixes a warning message that change causes

Update flake.nix to match adwaita-icon-theme being moved to top-level

---

src/bar.rs
src/clients/wayland/wl_output.rs
src/macros.rs
src/popup.rs

Popups will now instantly reposition themselves to be correctly placed on resolution change. This includes orientation and scale changes.
Fixes #610

fix(popup): incorrect pos when resolution changes

---

src/modules/workspaces.rs

Should solve https://github.com/JakeStanger/ironbar/issues/731 by printing a warning instead of stopping the receiving loop when focusing a workspace.

fix(workspaces): prevent crash when clicking current workspace

---

src/modules/mod.rs

fix: `on_scroll` events broken on touchpad

---

Cargo.lock
Cargo.toml
src/clients/mod.rs
src/main.rs
src/modules/tray/diff.rs
src/modules/tray/icon.rs
src/modules/tray/interface.rs
src/modules/tray/mod.rs

This PR, accompanied by https://github.com/JakeStanger/system-tray/pull/2 includes a *very* long-overdue set of fixes for the tray module.
Effectively:
- A proper (mostly, I think) spec-compliant host has been ported from eww by @ToxicMushroom which means Ironbar plays a lot nicer with other trays now.
- The eww code and some additional fixes mean that Ironbar is more tolerant to the ***many*** non-spec complaint programs out there. Although it's not perfect, this means:
- Icons should be a lot less likely to not show.
- Icons should be a lot less likely to duplicate.
- Tray icons now correctly receive updates, which means you'll see for example `nm-applet` animate when connecting.
- Menu separators now show.
- Menu items will now show their icons (check out VLC!).
- Any funny situations …

A whole load of tray fixes :tada:

---

src/modules/tray/interface.rs

each call to set_menu_widget registered a new event handler, resulting in multiple popups to be created. each popup tried to issue a grab with the same serial.
prevent this by disconnecting any previously registered handler.

tray: prevent widget buttons from piling up

---

docs/modules/Workspaces.md
examples/style.css
src/clients/compositor/hyprland.rs
src/clients/compositor/mod.rs
src/clients/compositor/sway.rs
src/modules/workspaces.rs

Allow highlighting a workspace which contains a window that triggered a urgent event, i.e., requests attention. In my case, I see it happens when I clink a link and it opens in a new tab on firefox, and when displaying a `BEL` character in some terminal emulators (at least in alacritty).
You can test it by running
```sh
sleep 1 && tput bel
```
in alacritty, and switching to another workspaces before the sleep expires.
I implemented it for both Sway and Hyprland. Sway keep track of a `urgent` flag for each client, and notify ironbar about changes. Hyprland or the other hand only contains a urgent event that triggers once, so I clean the urgent state of a workspace whenever it is focused.

feat: add `.urgent` workspace css class

---

docs/modules/Launcher.md
src/clients/wayland/mod.rs
src/clients/wayland/wlr_foreign_toplevel/handle.rs
src/clients/wayland/wlr_foreign_toplevel/mod.rs
src/modules/launcher/item.rs
src/modules/launcher/mod.rs

This PR adds a new config option `minimize_focused` to the launcher module, which when set to true will minimize the currently focused window if its icon is clicked. If there is more than a single window open of that particular application the normal focus behavior will occur.
I haven't written much rust before, but hopefully it's relatively problem free!
Resolves  #658

feat: Minimize focused window option for launcher

---

src/clients/compositor/sway.rs
src/modules/workspaces.rs

Simple enough to propagate the event of the rename.
However I'm not sure how to fix the order on rename, it doesn't seem to work if I just add
```rust
if self.sort == SortOrder::Alphanumeric {
reorder_workspaces(&container);
}
```

sway: support workspace rename events

---

docs/modules/Launcher.md
src/modules/launcher/item.rs

See the (now closed) #813 for more info.

feat(launcher): open new window on middle-click

---

Cargo.lock
Cargo.toml
build.rs
docs/Compiling.md
nix/default.nix
src/cli.rs

Auto-generated with clap.
Note: May be ideal to replace some of the sub-commands with flags to decrease the amount of generated man pages.
Edit: Draft while I think of something better to do here

feat: add shell completions

---

docs/modules/Clock.md
docs/modules/Custom.md
src/config/common.rs
src/config/mod.rs
src/modules/clock.rs
src/modules/custom/label.rs

Provides a way for the user to align text in these modules. Particularly useful with multi-line text. Equivalent to this would be CSS's ``text-align`` property (which, for God knows what reason, GTK CSS does not provide).
These seemed to be the best fitting modules to add this property to, but I'm open to adding it to more if there are any others that seem deserving of it to someone else.

feat: justify property for clock and custom label

---

Cargo.toml
docs/Compiling.md
docs/_Sidebar.md
docs/modules/Keyboard.md
docs/modules/Keys.md
nix/default.nix
src/clients/compositor/hyprland.rs
src/clients/compositor/mod.rs
src/clients/compositor/sway.rs
src/clients/mod.rs
src/config/mod.rs
src/image/gtk.rs
src/modules/keyboard.rs
src/modules/keys.rs
src/modules/mod.rs
src/modules/workspaces/mod.rs

Displays the current keyboard layout. Clicking switches to the next layout. Supports images. See `docs/` for details.
Resolves https://github.com/JakeStanger/ironbar/issues/575.
Current concerns:
1. `keyboard_layout` is a clear name, but maybe it's too verbose?
2. Is it okay to add yet another channel in `hyprland::Client`?
3. Maybe I should rename `layout_map` to `name_map` to be consistent with workspaces module?

feat: keyboard layout module

---

src/modules/volume.rs

feat(volume): add pango support to button

---

.idea/runConfigurations/Run__Live_Config_.xml
src/clients/wayland/mod.rs
src/clients/wayland/wlr_data_control/mod.rs
src/clients/wayland/wlr_data_control/offer.rs

Wayland spec says clients should read the offers they request receive on.
Ironbar was failing to do this because the event loop it used could get deadlocked on reading a pipe.
This pr fixes that by switching to tokio's async readers 
Thanks @zeroeightysix

Fixes clipboard deadlocking data sources

---

Cargo.lock
Cargo.toml
src/clients/mod.rs
src/clients/networkmanager.rs
src/clients/swaync/dbus.rs
src/clients/swaync/mod.rs
src/clients/upower/device.rs
src/clients/upower/mod.rs
src/clients/upower/upower.rs
src/modules/upower.rs

Also drops the deprecated `upower-dbus` crate

refactor: upgrade to zbus v5

---

src/clients/compositor/hyprland.rs
src/clients/compositor/sway.rs
src/modules/keyboard.rs

Not sure of the implications of increasing capacity but I don't think it's really a problem.
Switched event loop to avoid ending on `RecvError::Lagged` response.

keyboard: fix panic when layout update channel lags behind

---

docs/modules/Custom.md
docs/modules/Label.md
docs/modules/Launcher.md
src/modules/custom/label.rs
src/modules/label.rs
src/modules/launcher/mod.rs
src/modules/launcher/pagination.rs

Adds `page_size` option to launcher module. Adds truncation option to label module/widget.
Resolves #633

Launcher pagination and label truncation options

---

docs/Ironvars.md
src/clients/mod.rs
src/clients/sysinfo.rs
src/dynamic_value/dynamic_bool.rs
src/dynamic_value/dynamic_string.rs
src/ipc/commands.rs
src/ipc/server/ironvar.rs
src/ironvar.rs
src/main.rs
src/modules/sysinfo/mod.rs
src/modules/sysinfo/parser.rs
src/modules/sysinfo/renderer.rs
src/modules/sysinfo/token.rs

This is the alternative idea in #142. Since the overhaul plus this now make it very easy to find which variables are available, I don't think the main suggestion in that issue is needed.
When a `sys_info` module is configured on the bar, a `sysinfo` namespace will appear in the Ironvar list. 
The following are all valid:
```
ironbar var list
ironbar var list sysinfo
ironbar var list sysinfo.disk_percent
ironbar var get sysinfo.disk_percent./home
ironbar var get sysinfo.disk_percent.mean
ironbar var get sysinfo.memory_percent 
```
Resolves #142.

feat(sysinfo): expose values as ironvars

---

docs/Configuration guide.md
docs/modules/Custom.md
docs/modules/Network-Manager.md
docs/modules/Notifications.md
src/config/impl.rs
src/config/layout.rs
src/config/mod.rs
src/image/gtk.rs
src/modules/clipboard.rs
src/modules/clock.rs
src/modules/custom/button.rs
src/modules/custom/label.rs
src/modules/custom/mod.rs
src/modules/focused.rs
src/modules/keyboard.rs
src/modules/label.rs
src/modules/launcher/item.rs
src/modules/launcher/mod.rs
src/modules/launcher/pagination.rs
src/modules/music/config.rs
src/modules/music/mod.rs
src/modules/script.rs
src/modules/sway/mode.rs
src/modules/sysinfo/mod.rs
src/modules/tray/mod.rs
src/modules/upower.rs
src/modules/volume.rs
src/modules/workspaces/button.rs
src/modules/workspaces/mod.rs

Adds `orientation` and `justify` options to all modules and custom widgets where it makes sense to do so.
Any modules without support document this. Widgets fully document the options inline where present for now.
Resolves #296

feat: fully implement orientation/justify options

---

src/clients/compositor/mod.rs
src/clients/mod.rs
src/image/gtk.rs
src/image/mod.rs

build: decouple `workspace` and `keyboard` modules

---

src/clients/compositor/niri/mod.rs

Niri has a "[Named Workspaces](https://github.com/YaLTeR/niri/wiki/Configuration:-Named-Workspaces)" feature, 
where Workspace's id are assigned based on the order declared in the configuration file. 
However, when Ironbar initializes, the WorkspacesChanged event output by Niri is not sorted by ID. As a result, even when I declare `sort = "added"` in Ironbar's configuration file, the final sorting remains inconsistent. 
To achieve the expected behavior, we simply need to sort new_workspaces by ID before initializing workspaces in Ironbar. This change will not affect the original functionality.
This is my ironbar workspaces configuration
```
[[start]]
type = "workspaces"
sort = "added"
[start.name_map]
NETW = " NETW  "
TERM = " TERM  "
CODE = " CODE  "
CHAT = " CHAT  "
GAME = " GAME  …
```

refactor: sort niri workspaces before WorkspaceUpdate::Init

---

Cargo.toml
docs/Compiling.md
src/config/mod.rs
src/modules/mod.rs

All modules can now be toggled at compile time by feature flags

build: add feature flags for `custom`, `label`, `script` modules

---

src/modules/notifications.rs

Replaced the overlay_pass_through call following the migration notes doc: https://docs.gtk.org/gtk4/migrating-3to4.html#adapt-to-changes-in-gtkoverlay-api
Now it successfully compiles and on the first glance seems to be behaving the same as the gtk3 version, so hopefully a little bit of help towards #112 :crossed_fingers:

fix(notifications): gtk4 port

---

Cargo.lock
Cargo.toml
src/clients/libinput.rs
src/clients/mod.rs
src/clients/wayland/wlr_data_control/mod.rs
src/clients/wayland/wlr_data_control/offer.rs
src/clients/wayland/wlr_data_control/source.rs

Switches from the `input` crate to new async `colpetto`. Less janky to work with, and comes with noticeable performance improvements.

refactor(keys): switch to `colpetto`

---

.github/workflows/build.yml
.github/workflows/schema.yml
.github/workflows/wiki.yml
src/clients/wayland/mod.rs
src/clients/wayland/wl_seat.rs
src/clients/wayland/wlr_data_control/mod.rs

This allows Ironbar to run on a wider range of compositors, where support for the `wlr_foreign_toplevel` protocol used by focused/launcher, and the `wlr_data_control_device` protocol used by clipboard is missing.

fix(wayland): panicking on compositors without protocol support

---

.github/workflows/build.yml
Cargo.toml
docs/GTK4.md
docs/_Sidebar.md
docs/modules/Bindmode.md
src/clients/compositor/hyprland.rs
src/clients/compositor/mod.rs
src/clients/compositor/sway.rs
src/clients/mod.rs
src/config/mod.rs
src/modules/bindmode.rs
src/modules/mod.rs
src/modules/sway/mod.rs

I am currently migrating from sway to Hyprland, and so I added support for Hyprland in the sway_mode module. Because the module is no longer sway-only, I decided to rename to a more generic name. This feature does not have a consistent name across window managers, i3/Sway [calls it binding mode](https://i3wm.org/docs/userguide.html#binding_modes), while Hyprland calls it [Keybind submaps](https://wiki.hyprland.org/Configuring/Binds/#submaps). But "bindmode" appears to be a good enough name.
I made "sway_mode" be a alias for "bindmode" to avoid breaking configs that use the previous name, but I can remove that if you prefer.

feat: rename sway_mode to bindmode and add Hyprland support

---

src/modules/music/mod.rs

Closes #967
As for the UI I think the convention is to:
- Not pad it with zeros
- Only display hours if track duration is longer than 60 minutes
For instance, that's how SoundCloud displays duration.

fix(music): Fix hours not being displayed in track duration

---

src/modules/bindmode.rs

Closes #982
This works but I'm not sure how to also make it hidden upon initialization (needed because there would be no `BindModeUpdate`'s at this point yet). Tried to insert `label.hide()` right after building the widget but it doesn't work.

fix(bindmode): hide bindmode label if it's empty

---

src/modules/clipboard.rs
src/modules/clock.rs
src/modules/custom/mod.rs
src/modules/launcher/mod.rs
src/modules/mod.rs
src/modules/music/mod.rs
src/modules/upower.rs
src/modules/volume.rs

Removes unnecessary `tx` and `rx` params as values were always directly from context, which is also passed.

refactor(module): remove redundant `into_popup` parameters

---

src/modules/clock.rs

Closes #931
Additional context #931
So I chose to go with using selections. I think markings have a few cons:
- Would need to somehow style it because by default it's just bold text, much less noticeable than selections. I checked [adw-gtk3](https://github.com/lassekongo83/adw-gtk3) and couldn't find a selector for the marked day.
- Would need to also hook into `connect_{next,prev}_{month,year}` to unmark currently marked day, because marks persist across month/year changes (only a *day* is marked, and not a *date*).
- Would still need to do something with selections, because them being there without user having actually selected anything might be confusing. E.g. boot PC on Monday, open calendar on Wednesday, Monday is selected for some reason.
All in all it's a lot less code and problems …

fix(clock): reset selected calendar date on each popup open

---

nix/module.nix

This makes it more semantically approachable IMO.
I would expect this behavior:
- Default value is `null`
- Config is created if the value is not `null`
- Option unset (i.e. the default) => no config created
- This matches a lot of other HM modules
Currently it's this behavior (makes little sense to me):
- Default value is `{}`
- Config is created if the values is not `""`
- Need to explicitly set the option to `""` in order to not create a config
This would be a breaking change for:
- People who were setting the option to `""` to achieve not creating a config
- (Contrived) People who needed some sort of a nonsense config like `{}`

fix(nix): default HM module `config` option to `null`

---

docs/modules/Volume.md
src/modules/volume.rs

Part of #1011
As noted in the issue, I'm still down for marquee/rotation effect, but truncation would be an easy start.

feat(volume): Add `truncate` option for `volume` popup

---

src/modules/upower.rs

Was getting stuff like this on my ThinkPad T480:
I think it was because it has two batteries. Anyway, this PR makes sure the number is rounded

UPower: Round battery percent to whole number

---

src/bar.rs
src/config/mod.rs

If an individual controller fails, it will now error independently and allow other modules to continue loading.
Fixes #1057

fix: panic when module controller errors

---

src/desktop_file.rs

For chrome based desktop apps, i.e. apps launched with google-chrome --app=https://example.com,
`chrome-example.com__-Default` is the class  - notice D capital in Default). The find fails and no icon is pulled up. This makes the lookup case insensitive.

fix(desktop_file): case-insensitive app_id -> desktop_file find

---

docs/Configuration guide.md
src/config/common.rs
test-configs/custom-scroll.corn

Adds a new common option `smooth_scroll_speed` which controls the speed at which scroll events are emitted when scrolling on a trackpad, and using `on_scroll_up` and `on_scroll_down`.
Resolves #775

feat: smooth scrolling speed option

---

src/image/gtk.rs
src/image/mod.rs
src/modules/menu/ui.rs
src/modules/music/mod.rs
src/modules/notifications.rs
src/modules/upower.rs

These modules should now offer more control over the icons, allowing images and textual icons, and ensuring they work with the overrides system.
Resolves #511

feat(menu, notifications, upower): use ironbar image system

---

Cargo.lock
Cargo.toml
src/modules/music/mod.rs

Rather than some complicated regex based token replace system...we can just perform a bunch of `.replace` calls on the string for the token literals...
Groundbreaking.
Fixes #1139

refactor(music): remove regex dependency

---

src/bar.rs

- [fix(autohide): hiding bar when some widgets hovered](https://github.com/JakeStanger/ironbar/commit/caa1bf0f82378bb8533b2dec9f483f4d4e0917d0)
- [fix(autohide): hiding bar when leaving and re-entering within timeout](https://github.com/JakeStanger/ironbar/commit/c6a1670049081b66079fd840cf23421579ac1b25)
Fixes #1111

Autohide fixes

---

src/config/common.rs
src/modules/mod.rs

For button-type modules, although it was possible to disable the popup, it was not possible to attach an `on_click` listener. This is now fixed
Fixes #906
Fixes #1112

fix: `on_click` events not working on button widgets

---

docs/modules/Bluetooth.md

Not adding `"` around the type was causing a config error :
```
2025-09-09T09:51:08.523989Z ERROR ironbar: 345: Failed to load config:   --> 55:12
|
55 |     type = bluetooth
|            ^---
|
= expected object, array, boolean, null, string, integer, float, or input
```
Hope this will help someone !

doc(fix): bluetooth type not interpreted as string in corn config example

---

src/bar.rs
src/config/common.rs
src/modules/battery.rs
src/modules/clipboard.rs
src/modules/networkmanager.rs
src/modules/volume.rs
src/modules/workspaces/mod.rs

Hi, 
This migrate the volume and upower modules to gtk4

refactor: ported upower,volume,networkmanager modules to gtk4
